version: '3.7'

services:
  web:
    build: ./services/web
    restart: always
    # command: python manage.py run -h 0.0.0.0
    # command: bash -c 'while !</dev/tcp/db/5432; do sleep 3; done; bash /usr/src/app/scripts/docker_script.sh'
    command: bash -c 'bash /usr/src/app/scripts/docker_script.sh'
    volumes:
      - ./services/web/:/usr/src/app/
      - ../img_repo/:/usr/src/img_repo/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    environment:
      - APP_TYPE=FLASK_APP
    depends_on:
      - db
      - detector_worker
      - embedder_worker
  detector_worker:
    build: ./services/worker
    restart: always
    volumes:
      - ./services/worker/:/usr/src/worker/
      - ../img_repo/:/usr/src/img_repo/
    env_file:
      - ./.env.dev
    environment:
      - QUEUE=detector
    depends_on:
      - redis
  embedder_worker:
    build: ./services/worker
    restart: always
    volumes:
      - ./services/worker/:/usr/src/worker/
      - ../img_repo/:/usr/src/img_repo/
    env_file:
      - ./.env.dev
    environment:
      - QUEUE=embedder
    depends_on:
      - redis
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
volumes:
  postgres_data:
