version: '3.7'

services:
  web:
    build: ./services/web
    restart: always
    # command: python manage.py run -h 0.0.0.0
    # command: bash -c 'while !</dev/tcp/db/5432; do sleep 3; done; bash /usr/src/app/scripts/docker_script.sh'
    command: bash -c 'bash /usr/src/app/scripts/docker_script.sh'
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  facedetector:
    build: ./services/face_detector
    # restart: always
    volumes:
      - ./services/face_detector/:/usr/src/detector/
    ports:
      - 5001:5001
    env_file:
      - ./.env.dev
    depends_on:
      - redis
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
volumes:
  postgres_data:
